"""
Base Strategy Class - All trading strategies inherit from this
Ensures consistent interface and metrics calculation
"""

from abc import ABC, abstractmethod
import pandas as pd
import numpy as np
from typing import Dict, List, Tuple, Optional
from dataclasses import dataclass
from datetime import datetime


@dataclass
class Signal:
    """Trade signal generated by strategy"""
    ticker: str
    date: datetime
    price: float
    signal_type: str  # 'BUY', 'SELL'
    strength: float  # 0-100
    thesis: str  # Why did we generate this signal?
    stop_loss: float
    target_1: float
    target_2: float
    metadata: Dict = None


class BaseStrategy(ABC):
    """Abstract base class for all trading strategies"""
    
    def __init__(self, name: str, risk_per_trade: float = 0.01):
        self.name = name
        self.risk_per_trade = risk_per_trade
        self.signals: List[Signal] = []
        
    @abstractmethod
    def calculate_indicators(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Calculate all indicators needed for this strategy.
        Should modify df in-place and return it.
        """
        pass
    
    @abstractmethod
    def generate_signals(self, df: pd.DataFrame) -> List[Signal]:
        """
        Generate trade signals from the data.
        Should return list of Signal objects.
        """
        pass
    
    def backtest(self, df: pd.DataFrame, initial_capital: float = 5000.0,
                 commission: float = 0.001, slippage: float = 0.0005) -> Dict:
        """
        Run backtest on this strategy.
        Returns metrics dict.
        """
        df = self.calculate_indicators(df.copy())
        signals = self.generate_signals(df)
        
        if not signals:
            return {
                'total_return': 0.0,
                'win_rate': 0.0,
                'profit_factor': 0.0,
                'trades': 0,
                'error': 'No signals generated'
            }
        
        # Simple backtest logic - to be extended
        trades = []
        equity = initial_capital
        
        return {
            'total_return': (equity - initial_capital) / initial_capital,
            'final_equity': equity,
            'trades': len(trades),
            'win_rate': 0.0 if not trades else len([t for t in trades if t['pnl'] > 0]) / len(trades),
            'profit_factor': 1.0,
        }
    
    def validate_signal(self, signal: Signal) -> Tuple[bool, str]:
        """
        Validate that a signal meets minimum standards.
        Returns (is_valid, reason)
        """
        if signal.strength < 30:
            return False, "Signal strength too low"
        
        if signal.stop_loss >= signal.price:
            return False, "Stop loss must be below entry"
        
        if signal.target_1 <= signal.price:
            return False, "Target must be above entry"
        
        return True, "Valid"
    
    def position_size(self, account_equity: float, entry_price: float,
                     stop_loss: float, risk_pct: Optional[float] = None) -> float:
        """
        Calculate position size based on ATR-style risk model.
        
        Args:
            account_equity: Current account equity
            entry_price: Entry price
            stop_loss: Stop loss price
            risk_pct: Risk per trade (default: self.risk_per_trade)
        
        Returns:
            Number of shares to buy
        """
        if risk_pct is None:
            risk_pct = self.risk_per_trade
        
        risk_amount = account_equity * risk_pct
        risk_per_share = abs(entry_price - stop_loss)
        
        if risk_per_share == 0:
            return 0
        
        position_size = int(risk_amount / risk_per_share)
        return position_size
    
    def summary(self) -> Dict:
        """Return strategy summary"""
        return {
            'name': self.name,
            'signals_generated': len(self.signals),
            'risk_per_trade': self.risk_per_trade,
        }
